### PR TITLE
Making comment for admin

### PR DESCRIPTION
**Pull request by tanguyguillo**
After making post admin 

Capture d’écran 2022-08-08 à 21 15 58

We have to do the comment admin

### CODE REVIEW

**Comment by tanguyguillo** [comment]
Estimation : hald day, i prepared the interface

Capture d’écran 2022-08-08 à 21 26 25

**Comment by tanguyguillo** [comment]
Done :

Capture d’écran 2022-08-09 à 18 52 27

**Review by castroCrea — APPROVED** [review]

**Comment by tanguyguillo** [comment]
this branch is outdated and all thd works

**Comment by tanguyguillo** [comment]
have been approved these changes  and is already commit

**Pull request closed without merging**
